import bcrypt from "bcryptjs";
const data = {
	users: [
		{
			name: "Maroua",
			email: "maroua2012@gmail.com",
			password: bcrypt.hashSync("1234", 8),
			isAdmin: true,
		},
		{
			name: "Manel",
			email: "manel@gmail.com",
			password: bcrypt.hashSync("12dsd4", 8),
			isAdmin: false,
		},
	],
	products: [
		{
			name: "Nike Slim Shirt1",
			category: "Shirts",
			image: "../images/nike.png",
			price: 120,
			countInStock: 10,
			brand: "Nike",
			rating: 4.5,
			numReviews: 10,
			description: "High quality product",
		},
		{
			name: "Adidas fit shirt2",
			category: "Shirts",
			image: "../images/adida.png",
			price: 100,
			countInStock: 20,
			brand: "Adidas",
			rating: 4.0,
			numReviews: 10,
			description: "High quality product",
		},
		{
			name: "Lacoste Free Shirt3",
			category: "Shirts",
			image: "../images/lacoste.png",
			price: 220,
			countInStock: 0,
			brand: "Lacoste",
			rating: 4.8,
			numReviews: 17,
			description: "High quality product",
		},
		{
			name: "Nike Slim Shirt4",
			category: "Pants",
			image: "../images/p1.2.png",
			price: 78,
			countInStock: 5,
			brand: "Nike",
			rating: 4.5,
			numReviews: 10,
			description: "High quality product",
		},
		{
			name: "Puma Slim Pant5",
			category: "Pants",
			image: "../images/p1.3.png",
			price: 120,
			countInStock: 12,
			brand: "Puma",
			rating: 4.9,
			numReviews: 14,
			description: "High quality product",
		},
		{
			name: "Adidas Fit Pant6",
			category: "Pants",
			image: "../images/adida.png",
			price: 100,
			countInStock: 0,
			brand: "Adidas",
			rating: 4.5,
			numReviews: 17,
			description: "High quality product",
		},
	],
};

export default data;
